# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
    my_name = "Hello there Jayakrishnan"
    puts "#{my_name}"
    sh('pwd')

    #sh('bundle exec run get_info_plist_value parameter1:"CFBundleVersion" parameter2:"CFBundleShortVersionString"')
    #sh('env')
    sh('get_info_plist_value(path: './Info.plist", key: "CFBundleShortVersionString')')
    #identifier = get_info_plist_value(path: "./Info.plist", key: "CFBundleVersion")
    # version_number = get_info_plist_value(path: "../FastlaneTest/Info.plist", key: "CFBundleShortVersionString")
    # build_number = get_info_plist_value(path: "../FastlaneTest/Info.plist", key: "CFBundleVersion")
    #build_number = lane_context[SharedValues::BUILD_NUMBER]
    puts "#{my_name}"
    puts "#{build_number}"

  end

  lane :tests do
    run_tests(workspace: "FastlaneTest.xcworkspace",
              devices: ["iPhone 11"],
              scheme: "FastlaneTest")
  end

  lane :beta do
  build_app(scheme: "FastlaneTest",
            workspace: "FastlaneTest.xcworkspace",
            include_bitcode: true)
  end


end
